### ISSUE TITLE
Send Email on Quiz Taker Post

### ISSUE THREAD

**Issue by TrinityTerry** [Urban-Green-Lab/application#15]
Send an email to the quiz taker after they have taken the quiz

**Given**: The admin user wants an email to be sent to the user after a quiz taker takes a quiz
**When**: the backend gets a post request on the quiz taker endpoint
**Then**: An email should be sent to the user with the email template created in #14

## Steps
- [ ] Add Django variables to HTML template
- [ ] Set up email on post to quiz taker endpoint if the event is not in child mode

**Comment by RefreshingChi** [comment]
EMAILDATAModel
  quiz_taker.email ->email
  quiz_taker.fname -> fname
  quiz_taker.lname -> lname
  quiz_taker.score -> score
  events.name  -> event_name
  quiz_bank.name -> quiz_name
  QuizQuestionAnswer ( There will be multiple of these)
       question_bank.question -> question
       question_bank.info_link -> info_link
       question_bank_answers -> answer (THIS IS ONLY THE CORRECT ANSWER TO THE QUESTION)

**Comment by RefreshingChi** [comment]
We also need to have the Logo and the links to their site
