### ISSUE TITLE
Default Error Handling

### ISSUE THREAD

**Issue by ankajgoel** [Urban-Green-Lab/application#52]
if while entering data into home Signup page/Form or while user is taking questions, if UI crashes or api returns a 5xx or 4xx to front end, display an error page with a link to homePage or to start over.

e.g.
<img width="801" alt="Screen Shot 2020-10-29 at 2 13 12 PM" src="https://user-images.githubusercontent.com/9313208/97621418-e339e600-19f0-11eb-997a-8fab1d9a5e9c.png">

**Comment by drteresavasquez** [comment]
created _redirects file for this.
