### ISSUE TITLE
Question View | The answer choices are not getting disabled after user selects an option

### ISSUE THREAD

**Issue by ankajgoel** [Urban-Green-Lab/application#68]
<img width="513" alt="Screen Shot 2020-10-30 at 6 40 31 AM" src="https://user-images.githubusercontent.com/9313208/97701092-e1b50000-1a7a-11eb-956a-2aa19011aad2.png">

1. Launch the app https://deploy-preview-64--uglapp.netlify.app/quiz/1
2. Enter the information
3. click on Let's play
4. Now answer a wrong choice on question 1. User score 0
5. but immediately click on Right one, user gets points.
5b. Keep clicking on right answer over and over till timer runs out

Since answer choices are not disabled user can keep on clicking the right answer and get points

**Comment by drteresavasquez** [comment]
Yes. These are all things we will handle during styling. Functionality is there.
